steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/$PROJECT_ID:$SHORT_SHA', '.']
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/$PROJECT_ID/$PROJECT_ID:$SHORT_SHA']
- name: 'gcr.io/cloud-builders/gke-deploy'
  args:
  - run
  - --filename=anyway-backend.yaml
  - --image=gcr.io/$PROJECT_ID/$PROJECT_ID:$SHORT_SHA
  - --location=europe-west3
  - --cluster=anyway-dev-cluster-1
  - en