steps:
# build anyway-backend image
- name: 'docker/compose'
  args: ['build', '-f', 'docker-compose-cloud.yml', '--build-arg', PROJECT_ID=$PROJECT_ID', '--build-arg', 'COMMIT_SHA=$COMMIT_SHA']
- name: 'gcr.io/cloud-builders/gke-deploy'
  args:
  - run
  - --filename=anyway-backend.yaml
  - --image=eu.gcr.io/$PROJECT_ID/$PROJECT_ID:$COMMIT_SHA
  - --location=europe-west3
  - --cluster=anyway-dev-cluster-1
  - en