steps:
# build anyway-backend image
- name: 'docker/compose'
  args: ['build']
  env:
  - 'ANYWAY_BACKEND_IMG=$PROJECT_ID:$COMMIT_SHA'
  - 'ANYWAY_BACKEND_DB_IMG=$PROJECT_ID-db:$COMMIT_SHA'
- name: 'gcr.io/cloud-builders/docker'
  args: ['tag', '$ANYWAY_BACKEND_IMG', 'eu.gcr.io/$PROJECT_ID/$PROJECT_ID:$COMMIT_SHA']
- name: 'gcr.io/cloud-builders/docker'
  args: ['tag', '$ANYWAY_BACKEND_DB_IMG', 'eu.gcr.io/$PROJECT_ID/$PROJECT_ID-DB:$COMMIT_SHA']

# push anyway-backend image into cloud repository
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'eu.gcr.io/$PROJECT_ID/$PROJECT_ID:$COMMIT_SHA']
# deploy anyway-backend image into kubernetes 
- name: 'gcr.io/cloud-builders/gke-deploy'
  args:
  - run
  - --filename=anyway-backend.yaml
  - --image=eu.gcr.io/$PROJECT_ID/$PROJECT_ID:$COMMIT_SHA
  - --location=europe-west3
  - --cluster=anyway-dev-cluster-1
  - en