steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/$BUILD_ID', '.']
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/$PROJECT_ID/$BUILD_ID']
- name: 'gcr.io/cloud-builders/gke-deploy'
  args:
  - run
  - --image=gcr.io/$PROJECT_ID/$BUILD_ID
  - --location=europe-west3
  - --cluster=anyway-dev-cluster-1