apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"apps/v1","kind":"Deployment","metadata":{"annotations":{},"labels":{"app.kubernetes.io/managed-by":"gcp-cloud-build-deploy"},"name":"anyway-backend","namespace":"default"},"spec":{"replicas":3,"selector":{"matchLabels":{"app":"anyway-backend"}},"template":{"metadata":{"labels":{"app":"anyway-backend","app.kubernetes.io/managed-by":"gcp-cloud-build-deploy"}},"spec":{"containers":[{"image":"gcr.io/anyway-backend/anyway-backend@sha256:aa469fc8d761b09b7a9aaa163bfe00126447f67a600dfd202a09e42e0edbb980","name":"anyway-backend"}]}}}}
  creationTimestamp: "2020-01-08T11:37:48Z"
  generation: 2
  labels:
    app.kubernetes.io/managed-by: gcp-cloud-build-deploy
  name: anyway-backend
  namespace: default
  resourceVersion: "52656"
  selfLink: /apis/apps/v1/namespaces/default/deployments/anyway-backend
  uid: 4bdecba9-320b-11ea-bdc8-42010a9c0093
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: anyway-backend
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: anyway-backend
        app.kubernetes.io/managed-by: gcp-cloud-build-deploy
    spec:
      containers:
      env: 
            - name: DATABASE_URL
                valueFrom:
                    secretKeyRef:
                        name: literal-token
                        key: DATABASE_URL
      - image: gcr.io/$PROJECT_ID/$PROJECT_ID:$BUILD_ID
        imagePullPolicy: IfNotPresent
        name: anyway-backend
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status:
  availableReplicas: 1
  conditions:
  - lastTransitionTime: "2020-01-08T11:38:26Z"
    lastUpdateTime: "2020-01-08T11:38:26Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  - lastTransitionTime: "2020-01-08T11:37:48Z"
    lastUpdateTime: "2020-01-08T11:38:26Z"
    message: ReplicaSet "anyway-backend-56c8cdc498" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  observedGeneration: 2
  readyReplicas: 1
  replicas: 1
  updatedReplicas: 1
